image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      psql -c "CREATE DATABASE sagacity_db;"
  - command: |
      psql -c "ALTER USER gitpod WITH PASSWORD 'gitpod';"

ports:
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers